//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesOnline.Models
{
    using System;
    using System.Collections.Generic;

    public partial class QuanTriVien
    {
        public string taiKhoanQTV { get; set; }
        public string matKhauQTV { get; set; }
        public string HoTen { get; set; }
        public string email { get; set; }
        public string soDT { get; set; }
        public string hinhDD { get; set; }
        public string newpass { get; set; }
        public string confirmpass{get;set;}
    }
}
